Repository Nexters/AZ-Server, pull requests merged in 2020-07, with the labels that each got.

#5 # feature/4
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle
  youtugo-api/build.gradle
  youtugo-application/build.gradle
  youtugo-application/src/main/java/org/nexters/az/YouTuGoApplication.java
  youtugo-application/src/main/java/org/nexters/az/config/.gitkeep
  youtugo-application/src/main/java/org/nexters/az/sample/controller/.gitkeep
  youtugo-application/src/main/java/org/nexters/az/sample/exception/.gitkeep
  youtugo-application/src/main/java/org/nexters/az/sample/request/.gitkeep
  youtugo-application/src/main/java/org/nexters/az/sample/response/.gitkeep
  youtugo-application/src/main/resources/.gitkeep
  youtugo-application/src/test/java/org/nexters/az/.gitkeep
  youtugo-application/src/test/resources/.gitkeep
  youtugo-core/build.gradle
  youtugo-core/src/main/java/org/nexters/az/.gitkeep
  youtugo-domain/build.gradle
  youtugo-domain/src/main/java/org/nexters/az/sample/entity/.gitkeep
  youtugo-domain/src/main/java/org/nexters/az/sample/exception/.gitkeep
  youtugo-domain/src/main/java/org/nexters/az/sample/repository/.gitkeep
  youtugo-domain/src/main/java/org/nexters/az/sample/service/.gitkeep
  youtugo-domain/src/main/resources/.gitkeep
  youtugo-domain/src/test/java/org/nexters/az/.gitkeep
  youtugo-domain/src/test/resources/.gitkeep
Labels: feat, setting

#13 exception handler 추가
  youtugo-application/src/main/java/org/nexters/az/filter/GlobalExceptionHandler.java
  youtugo-application/src/main/java/org/nexters/az/sample/controller/.gitkeep
  youtugo-application/src/main/java/org/nexters/az/sample/controller/IndexController.java
  youtugo-application/src/main/java/org/nexters/az/sample/exception/.gitkeep
  youtugo-application/src/main/java/org/nexters/az/sample/exception/TestNoFoundException.java
  youtugo-core/src/main/java/org/nexters/az/.gitkeep
  youtugo-core/src/main/java/org/nexters/az/exception/BadRequestException.java
  youtugo-core/src/main/java/org/nexters/az/exception/CanHaveStatusException.java
  youtugo-core/src/main/java/org/nexters/az/exception/ConflictException.java
  youtugo-core/src/main/java/org/nexters/az/exception/ForbiddenException.java
  youtugo-core/src/main/java/org/nexters/az/exception/NotFoundException.java
  youtugo-core/src/main/java/org/nexters/az/exception/UnauthorizedException.java
Labels: setting

#15 게시글 작성 API
  build.gradle
  youtugo-application/build.gradle
  youtugo-application/src/main/java/org/nexters/az/post/controller/PostController.java
  youtugo-application/src/main/java/org/nexters/az/post/request/WritePostRequest.java
  youtugo-application/src/main/java/org/nexters/az/post/response/WritePostResponse.java
  youtugo-application/src/main/resources/.gitkeep
  youtugo-application/src/main/resources/application.yml
  youtugo-domain/build.gradle
  youtugo-domain/src/main/java/org/nexters/az/common/entity/BaseTime.java
  youtugo-domain/src/main/java/org/nexters/az/common/repository/ExtendRepository.java
  youtugo-domain/src/main/java/org/nexters/az/post/dto/DetailedPost.java
  youtugo-domain/src/main/java/org/nexters/az/post/entity/Post.java
  youtugo-domain/src/main/java/org/nexters/az/post/repository/PostRepository.java
  youtugo-domain/src/main/java/org/nexters/az/post/service/PostService.java
  youtugo-domain/src/main/java/org/nexters/az/user/entity/User.java
  youtugo-domain/src/main/java/org/nexters/az/user/repository/UserRepository.java
Labels: feat

#18 exceptionHandler 변경
  youtugo-application/build.gradle
  youtugo-application/src/main/java/org/nexters/az/filter/GlobalExceptionHandler.java
  youtugo-core/src/main/java/org/nexters/az/exception/BadRequestException.java
  youtugo-core/src/main/java/org/nexters/az/exception/CanHaveStatusException.java
  youtugo-core/src/main/java/org/nexters/az/exception/ConflictException.java
  youtugo-core/src/main/java/org/nexters/az/exception/ForbiddenException.java
  youtugo-core/src/main/java/org/nexters/az/exception/NotFoundException.java
  youtugo-core/src/main/java/org/nexters/az/exception/UnauthorizedException.java
Labels: enhancement

#22 #11 - 게시글 검색(조회) API
  youtugo-application/src/main/java/org/nexters/az/YouTuGoApplication.java
  youtugo-application/src/main/java/org/nexters/az/config/.gitkeep
  youtugo-application/src/main/java/org/nexters/az/config/SwaggerFoxConfig.java
  youtugo-application/src/main/java/org/nexters/az/post/controller/PostController.java
  youtugo-application/src/main/java/org/nexters/az/post/request/WritePostRequest.java
  youtugo-application/src/main/java/org/nexters/az/post/response/GetPostsResponse.java
  youtugo-application/src/test/java/org/nexters/az/.gitkeep
  youtugo-application/src/test/java/org/nexters/az/AZApiApplicationTests.java
  youtugo-application/src/test/java/org/nexters/az/common/CommonTest.java
  youtugo-application/src/test/java/org/nexters/az/post/PostControllerTest.java
  youtugo-application/src/test/resources/.gitkeep
  youtugo-application/src/test/resources/application.yml
  youtugo-domain/build.gradle
  youtugo-domain/src/main/java/org/nexters/az/common/dto/SimplePage.java
  youtugo-domain/src/main/java/org/nexters/az/post/repository/PostRepository.java
  youtugo-domain/src/main/java/org/nexters/az/post/service/PostService.java
  youtugo-domain/src/main/java/org/nexters/az/user/dto/SimpleUser.java
  youtugo-domain/src/main/java/org/nexters/az/user/entity/User.java
Labels: feat, fix

#23 #20 코멘트 API 작성
  youtugo-application/src/main/java/org/nexters/az/comment/controller/CommentController.java
  youtugo-application/src/main/java/org/nexters/az/comment/request/WriteCommentRequest.java
  youtugo-application/src/main/java/org/nexters/az/comment/response/GetCommentsResponse.java
  youtugo-application/src/main/java/org/nexters/az/comment/response/WriteCommentResponse.java
  youtugo-domain/src/main/java/org/nexters/az/comment/dto/DetailedComment.java
  youtugo-domain/src/main/java/org/nexters/az/comment/entity/Comment.java
  youtugo-domain/src/main/java/org/nexters/az/comment/exception/CommentNotFoundException.java
  youtugo-domain/src/main/java/org/nexters/az/comment/exception/CommentUnauthorizedException.java
  youtugo-domain/src/main/java/org/nexters/az/comment/repository/CommentRepository.java
  youtugo-domain/src/main/java/org/nexters/az/comment/service/CommentService.java
Labels: feat

#32 # feature/21 - 게시글 상세보기/삭제 API 개발
  youtugo-application/src/main/java/org/nexters/az/post/controller/PostController.java
  youtugo-application/src/main/java/org/nexters/az/post/response/DeletePostResponse.java
  youtugo-application/src/main/java/org/nexters/az/post/response/GetPostResponse.java
  youtugo-application/src/test/java/org/nexters/az/post/PostControllerTest.java
  youtugo-domain/src/main/java/org/nexters/az/post/exception/NoPermissionDeletePostException.java
  youtugo-domain/src/main/java/org/nexters/az/post/exception/NonExistentPostException.java
  youtugo-domain/src/main/java/org/nexters/az/post/repository/PostRepository.java
  youtugo-domain/src/main/java/org/nexters/az/post/service/PostService.java
Labels: feat
